[ADD] #5 주간 날씨 테이블뷰 구현
iDrogba/WeatherApp pull request #11
Opened 2022-07-12 08:22 UTC by lenamin

#5 RegionWeatherViewController에 들어가는 주간 날씨를 받는 테이블뷰 구현

2022-07-12 10:26 UTC, iDrogba requested changes

2022-07-12 10:26 UTC, iDrogba commented on WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
> +            view.addSubview($0)
오 이런 방법도 있네요

2022-07-12 10:26 UTC, iDrogba commented on WeatherApp/WeatherApp/Models/WeekWeather.swift
> +
수요일 비비센터 시간에 만들어둔 날씨 모델 관련해서 설명 드리겠습니다

2022-07-12 10:26 UTC, iDrogba commented on WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
> +        label.shadowColor = UIColor(white: 150 / 255, alpha: 0.2)
반복적으로 사용되는 UIColor는 Asset에 Color Set 으로 추가 부탁드립니다!

2022-07-13 00:06 UTC, lenamin commented on WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
> +        label.shadowColor = UIColor(white: 150 / 255, alpha: 0.2)
넵!

2022-07-13 06:14 UTC, lenamin commented on WeatherApp/WeatherApp/Controllers/RegionWeatherViewController.swift
> +        label.shadowColor = UIColor(white: 150 / 255, alpha: 0.2)
[31eb350](https://github.com/iDrogba/WeatherApp/pull/11/commits/31eb350794f013bd2ce6644525225ffb216ed4db) 수정했습니다

2022-07-13 07:52 UTC, iDrogba approved these changes

2022-07-13 10:01 UTC, merged